### ISSUE TITLE
logical and operator

### ISSUE THREAD

**Issue by ghost** [vspinu/company-math#2] opened 2015-08-17 11:02 UTC
Hi and thank you for company-math using almost every day.

I have some problems completing the logical and operator with company-math-symbols-unicode

I have tried , \and ,\con , \logical etc. Is this something that could be fixed? 

best regards
Haakan

**Comment by vspinu** [comment] 2015-08-17 16:01
It could be easily fixed by adding those symbols to the corresponding lists in [math-symbol-list](https://github.com/vspinu/math-symbol-lists).

Do you know a place where a comprehensive list of such symbols and unicode equivalents could be found?

**Comment by ghost** [comment] 2015-09-10 08:08
Thanks so much, I found the list and I will add the symbols I need, I close this issue now

**Comment by vspinu** [comment] 2015-09-10 10:15
So could you provide a patch to the package? Or tell me where you got the list? Is it comprehensive?

**Comment by ghost** [comment] 2015-09-16 15:20
I'm sorry, my mistake. I will try to use the following document 
www.unicode.org/charts/PDF/U2200.pdf
to add the needed symbols one by one to math-symbols-list. I let you know when it's done

**Comment by cpitclaudel** [comment] 2016-02-27 23:06
Hi @vspinu,

Here are two lists:
- https://github.com/wspr/unicode-math/blob/master/unicode-math-table.tex , used by the unicode-math LaTeX package
- http://milde.users.sourceforge.net/LUCR/Math/, which provides a more comprehensive mapping (IIUC it supersedes the first link

Let me know if I can help! I maintain company-coq, which loads company-math by default.

**Comment by cpitclaudel** [comment] 2016-02-27 23:31
The `(defconst LaTeX-math-default` in `AucTeX`'s `latex.el` might also be of interest.

**Comment by vspinu** [comment] 2016-02-28 11:57
Thanks @cpitclaudel. The second is indeed more comprehensive, it is a list of 2751 symbols while `unicode-math` contains 2446. Company math is using 2622 distinct symbols. Unfortunately I forgot where I picked those from. 

In any case symbols that OP asks for are not in any of those lists (\and ,\con , \logical etc.). So I guess the standard defines those symbols under different names.

**Comment by vspinu** [comment] 2016-02-28 12:00
> The (defconst LaTeX-math-default in AucTeX's latex.el might also be of interest.

I think this is where I picked `math-symbol-list-basic` from. Only 517 symbols.

**Comment by vspinu** [comment] 2016-02-28 14:27
I have updated [math-symbol-list](https://github.com/vspinu/math-symbol-lists) package for LUCR database. I was missing only about 10 commands. 

The issue is that \and ,\con , \logical etc.  are not really standard names for those operators. For instance `LOGICAL AND` is `\wedge`.  LUCR lists include common synonyms for some commands. While we can idnclude those as well, I think it would enforce bad habits and create issues with plain latex by requering extra packages. 

For reference, if you are looking for a symbol check:
- [LUCR page](http://milde.users.sourceforge.net/LUCR/Math/unimathsymbols.xhtml), or
- [`math-symbol-list`](http://milde.users.sourceforge.net/LUCR/Math/unimathsymbols.xhtml) package directly

**Closed as completed by vspinu** 2016-02-28 14:27 UTC
